In [1]:
# Write a NumPy program to create an array of 10 zeros.
import numpy as np
arr = np.zeros(9)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
# Write a NumPy program to create an array of 10 ones.
arr =  np.ones(9)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
# Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:

np.array(([0,1,2],[3,4,5],[6,7,8]))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# Write a NumPy program to reverse an array (first element becomes the last)
a = np.array(([0,1,2],[3,4,5],[6,7,8]))
res = np.flip(a)
print(res)

[[8 7 6]
 [5 4 3]
 [2 1 0]]


In [11]:
# Write a NumPy program to extract all odd numbers from an array.
a = np.array(([0,1,2],[3,4,5],[6,7,8]))
a[a%2==1]

array([1, 3, 5, 7])

In [12]:
a = np.array(([0,1,2],[3,4,5],[6,7,8]))
if a%2==1:
    print(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [3]:
# Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array.
import numpy as np
x = np.random.randint(1,11,(4,4))
y = np.random.randint(1,11,(4,4))
print(f'the x array are \n{x}')
print(f'the y array are \n{y}')
print('-'*20)
print(f'the sum of array is : \n{x+y}')
print(f'the multiplication of array is : \n {x*y}')


the x array are 
[[ 6  6  2  6]
 [ 7  8  1  3]
 [ 8  9  8  7]
 [ 6  5 10  8]]
the y array are 
[[ 6  8  3  1]
 [ 2  7  9  9]
 [ 5  9 10  6]
 [ 4  8  1  1]]
--------------------
the sum of array is : 
[[12 14  5  7]
 [ 9 15 10 12]
 [13 18 18 13]
 [10 13 11  9]]
the multiplication of array is : 
 [[36 48  6  6]
 [14 56  9 27]
 [40 81 80 42]
 [24 40 10  8]]


In [18]:
# Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.
b = np.random.randint(0,11,(5,5))
print(b)
bmin ,bmax = x.min() , x.max()
print(f'the maximum value is:- {bmax}')
print(f'the minimum value is:- {bmin}')

[[10 10 10  6  4]
 [ 3  9  8  1  5]
 [ 8  5  5  4  5]
 [ 0  9  5  3  9]
 [ 3  8  3  1  7]]
the maximum value is:- 10
the minimum value is:- 1


In [2]:
# Write a NumPy program to create a 2D array with 1 on the border and 0 inside.
import numpy as np
x = np.array(([[1,0,1],[1,0,1]],[[1,0,1],[1,0,1]]))
print(x)

[[[1 0 1]
  [1 0 1]]

 [[1 0 1]
  [1 0 1]]]


In [4]:
# Write a NumPy program to find the unique elements of an array
import numpy as np
arr = np.array([3,3,4,5,6,5,6,4])
res = np.unique(arr)
print(res)

[3 4 5 6]


In [8]:
# Write a NumPy program to extract the elements in the odd-numbered columns of a 2D array.

import numpy as np
x = np.array(([[1,2,3],[5,2,6]],[[7,3,5],[7,4,3]]))
a = x[x%2==1]
print(a)
r = np.unique(a)
print(r)

[1 3 5 7 3 5 7 3]
[1 3 5 7]


In [9]:
# Write a NumPy program to extract the elements in the even-numbered rows of a 2D array.
import numpy as np
x = np.array(([[1,2,3],[5,2,6]],[[7,3,5],[7,4,3]]))
a = x[x%2==0]
print(a)
r = np.unique(a)
print(r)

[2 2 6 4]
[2 4 6]


In [ ]:
# Write a NumPy program to extract a subarray from a given array. The subarray should include the first 3 rows and the columns from index 1 to 4 (inclusive).



In [11]:
# Write a NumPy program to reverse the order of elements in each column of a 2D array.
x = np.array(([[1,2,3],[5,2,6]],[[7,3,5],[7,4,3]]))
a = np.flip(x)
print(a)

[[[3 4 7]
  [5 3 7]]

 [[6 2 5]
  [3 2 1]]]


In [14]:
import numpy as np
initial_array = np.array([[[1, 1, 1, 2],[2, 2, 2, 3],[3, 3, 3, 4]],[[1, 1, 1, 2],[2, 2, 2, 3],[3, 3, 3, 4]]])
index=0
initial_shape = initial_array.shape
reversed=np.empty(shape=initial_shape)
for inner_array in initial_array:
    reversed[index] = np.fliplr(inner_array)
    index += 1
print(f'the initial array is :- \n{initial_array}')
print(f'the reversed array is :- \n{reversed}')

the initial array is :- 
[[[1 1 1 2]
  [2 2 2 3]
  [3 3 3 4]]

 [[1 1 1 2]
  [2 2 2 3]
  [3 3 3 4]]]
the reversed array is :- 
[[[2. 1. 1. 1.]
  [3. 2. 2. 2.]
  [4. 3. 3. 3.]]

 [[2. 1. 1. 1.]
  [3. 2. 2. 2.]
  [4. 3. 3. 3.]]]


In [5]:
# Write a NumPy program to create a diagonal matrix from a given 1D array. The elements below the diagonal should be zero, and the elements above the diagonal should be squared

# create a diagonal matrix with the diagonal elements as 0
import numpy as np
matrix = np.diag([1, 2, 3, 4], k=0)
print(matrix)
# create a diagonal matrix with the diagonal elements as 1
matrix = np.diag([1, 2, 3, 4], k=1)
print(matrix)
atrix = np.diag([1, 2, 3, 4], k=-1)
print(atrix)
matrix = np.diag([1, 2, 3, 4], k=-2)
print(matrix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]]


In [11]:
# Write a NumPy program to create a diagonal matrix from a given 1D array. The elements below the diagonal should be zero, and the elements above the diagonal should be squared
import numpy as np
matrix = np.diag([1,4,9,0,1,2,3])
print(matrix)

[[1 0 0 0 0 0 0]
 [0 4 0 0 0 0 0]
 [0 0 9 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 2 0]
 [0 0 0 0 0 0 3]]
